services:
  clawdbot-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${CLAWDBOT_IMAGE:-clawdbot:local}
    environment:
      HOME: /home/node
      TERM: xterm-256color
      CLAWDBOT_GATEWAY_TOKEN: ${CLAWDBOT_GATEWAY_TOKEN}
      CLAUDE_AI_SESSION_KEY: ${CLAUDE_AI_SESSION_KEY}
      CLAUDE_WEB_SESSION_KEY: ${CLAUDE_WEB_SESSION_KEY}
      CLAUDE_WEB_COOKIE: ${CLAUDE_WEB_COOKIE}
      CLAWDBOT_USE_OPENCODE: ${CLAWDBOT_USE_OPENCODE:-false}
      CLAWDBOT_WHISPER_PRELOAD: ${CLAWDBOT_WHISPER_PRELOAD:-true}
      CLAWDBOT_WHISPER_MODEL: ${CLAWDBOT_WHISPER_MODEL:-base}
      CLAWDBOT_WHISPER_LANGUAGE: ${CLAWDBOT_WHISPER_LANGUAGE:-fr}
      XDG_CACHE_HOME: /opt/whisper-cache
    volumes:
      - ${CLAWDBOT_CONFIG_DIR}:/home/node/.clawdbot
      - ${CLAWDBOT_WORKSPACE_DIR}:/home/node/clawd
      - ${CLAWDBOT_USER_CONFIG_DIR}:/home/node/.config
      - ${CLAWDBOT_WHISPER_CACHE_VOLUME:-clawdbot-whisper-cache}:/opt/whisper-cache
    ports:
      - "${CLAWDBOT_GATEWAY_PORT:-18789}:18789"
      - "${CLAWDBOT_BRIDGE_PORT:-18790}:18790"
    init: true
    restart: unless-stopped
    command:
      [
        "node",
        "dist/index.js",
        "gateway-daemon",
        "--bind",
        "${CLAWDBOT_GATEWAY_BIND:-lan}",
        "--port",
        "${CLAWDBOT_GATEWAY_PORT:-18789}",
        "--allow-unconfigured"
      ]


  #clawdbot-cli:
  #  image: ${CLAWDBOT_IMAGE:-clawdbot:local}
  #  environment:
  #    HOME: /home/node
  #    TERM: xterm-256color
  #    BROWSER: echo
  #    CLAUDE_AI_SESSION_KEY: ${CLAUDE_AI_SESSION_KEY}
  #    CLAUDE_WEB_SESSION_KEY: ${CLAUDE_WEB_SESSION_KEY}
  #    CLAUDE_WEB_COOKIE: ${CLAUDE_WEB_COOKIE}
  #  volumes:
  #    - ${CLAWDBOT_CONFIG_DIR}:/home/node/.clawdbot
  #    - ${CLAWDBOT_WORKSPACE_DIR}:/home/node/clawd
  #  stdin_open: true
  #  tty: true
  #   init: true
  #  entrypoint: ["node", "dist/index.js"]
